[package]
name = "pahkat-cli"
version = "0.6.0"
authors = ["Brendan Molloy <brendan@bbqsrc.net>"]
edition = "2018"

[[bin]]
name = "pahkat"
path = "src/main.rs"

[dependencies]
pahkat-types = { path = "../pahkat-types" }
pahkat-common = { path = "../pahkat-common" }
clap = "2.33.0"
dialoguer = "0.5.0"
termcolor = "1.0.5"
pathdiff = "0.1.0"
url = "2.1.0"
serde = "1.0.102"
serde_json = "1.0.41"
reqwest = "0.9.22"

